version: '3.7'

services:

  isofh_frontend:
    container_name: isofh_frontend
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '/node_modules'
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production